spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-db
    username: test
    password: test@123
  jpa:
    show-sql: false
    hibernate.ddl-auto: create
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
org:
  jobrunr:
    job-scheduler:
      enabled: true
    dashboard:
      enabled: true
      port: 8085
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5 #check for new work every 5 seconds
      worker-count: 10 #this value normally is defined by the amount of CPU's that are available
      delete-succeeded-jobs-after: 36 #succeeded jobs will go to the deleted state after 36 hours
      permanently-delete-deleted-jobs-after: 72 #deleted jobs will be deleted permanently after 72 hours
    database:
      table-prefix: "project59_" # allows to set a table prefix
    jobs:
      default-number-of-retries: 10 #the default number of retries for a failing job
      retry-back-off-time-seed: 3 #the default time seed for the exponential back-off policy.
      metrics:
        enabled: true #Micrometer integration
